// <auto-generated />
using System;
using DotnetBoilerplate.Infrastructure.Migrations.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotnetBoilerplate.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250113093049_dbinit")]
    partial class dbinit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotnetBoilerplate.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("currency");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("customer_phone");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int")
                        .HasColumnName("payment_method_id");

                    b.Property<string>("PaymentOrderId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payment_order_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("DotnetBoilerplate.Domain.Entities.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("payment_methods", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 13, 9, 30, 48, 517, DateTimeKind.Utc).AddTicks(8415),
                            Name = "VNPay",
                            UpdatedAt = new DateTime(2025, 1, 13, 9, 30, 48, 517, DateTimeKind.Utc).AddTicks(8417)
                        });
                });

            modelBuilder.Entity("dotnet_boilerplate.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("roles_role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 13, 9, 30, 48, 368, DateTimeKind.Utc).AddTicks(2383),
                            Name = "admin",
                            UpdatedAt = new DateTime(2025, 1, 13, 9, 30, 48, 368, DateTimeKind.Utc).AddTicks(2384)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 13, 9, 30, 48, 368, DateTimeKind.Utc).AddTicks(2387),
                            Name = "member",
                            UpdatedAt = new DateTime(2025, 1, 13, 9, 30, 48, 368, DateTimeKind.Utc).AddTicks(2388)
                        });
                });

            modelBuilder.Entity("dotnet_boilerplate.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_joined");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsStaff")
                        .HasColumnType("bit")
                        .HasColumnName("is_staff");

                    b.Property<bool>("IsSuperUser")
                        .HasColumnType("bit")
                        .HasColumnName("is_superuser");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_login");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("users_user", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 13, 9, 30, 48, 517, DateTimeKind.Utc).AddTicks(8403),
                            DateJoined = new DateTime(2025, 1, 13, 9, 30, 48, 517, DateTimeKind.Utc).AddTicks(8403),
                            Email = "admin@email.com",
                            FullName = "Admin",
                            IsActive = true,
                            IsStaff = false,
                            IsSuperUser = true,
                            LastLogin = new DateTime(2025, 1, 13, 9, 30, 48, 517, DateTimeKind.Utc).AddTicks(8404),
                            Password = "$2a$11$Wi6bPQOYhCmUz3Aocja9KugllugDNZjlTDZtOxS3mfcpNxBTiUgCa",
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 1, 13, 9, 30, 48, 517, DateTimeKind.Utc).AddTicks(8407)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 13, 9, 30, 48, 517, DateTimeKind.Utc).AddTicks(8409),
                            DateJoined = new DateTime(2025, 1, 13, 9, 30, 48, 517, DateTimeKind.Utc).AddTicks(8410),
                            Email = "tien@email.com",
                            FullName = "Tien",
                            IsActive = true,
                            IsStaff = false,
                            IsSuperUser = false,
                            LastLogin = new DateTime(2025, 1, 13, 9, 30, 48, 517, DateTimeKind.Utc).AddTicks(8410),
                            Password = "$2a$11$Wi6bPQOYhCmUz3Aocja9KugllugDNZjlTDZtOxS3mfcpNxBTiUgCa",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 1, 13, 9, 30, 48, 517, DateTimeKind.Utc).AddTicks(8411)
                        });
                });

            modelBuilder.Entity("DotnetBoilerplate.Domain.Entities.Order", b =>
                {
                    b.HasOne("DotnetBoilerplate.Domain.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("dotnet_boilerplate.Domain.Entities.User", b =>
                {
                    b.HasOne("dotnet_boilerplate.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("dotnet_boilerplate.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
